server {
    server_name kissme.bj www.kissme.bj;
    root /var/www/wikconnect/frontend;

    location / {
        proxy_pass http://localhost:3000;
        proxy_http_version 1.1;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection 'upgrade';
        proxy_set_header Host $host;
        proxy_cache_bypass $http_upgrade;
    }

    location /_next/ {
        proxy_pass http://localhost:3000;
        proxy_http_version 1.1;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection 'upgrade';
        proxy_set_header Host $host;
        proxy_cache_bypass $http_upgrade;
        add_header Cache-Control "no-store, max-age=0, must-revalidate" always;
    }


    location /admin {
        proxy_pass http://localhost:3001;
        proxy_http_version 1.1;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection 'upgrade';
        proxy_set_header Host $host;
        proxy_cache_bypass $http_upgrade;
    }

    location /admin/_next/ {
        proxy_pass http://localhost:3001;
        proxy_http_version 1.1;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection 'upgrade';
        proxy_set_header Host $host;
        proxy_cache_bypass $http_upgrade;
        add_header Cache-Control "no-store, max-age=0, must-revalidate" always;
    }

    location /api {
    alias /var/www/wikconnect/api/public;
    try_files $uri $uri/ @api;
    
    location ~ \.php$ {
	include snippets/fastcgi-php.conf;	#timeout
        fastcgi_pass unix:/var/run/php/php8.3-fpm.sock;
	fastcgi_read_timeout 300;  # Augmenter le timeout
	fastcgi_send_timeout 300;
	fastcgi_connect_timeout 300;
	fastcgi_buffer_size 128k;
	fastcgi_buffers 4 256k;
	fastcgi_busy_buffers_size 256k;	#timeout
#        fastcgi_index index.php;
        include fastcgi_params;
        fastcgi_param SCRIPT_FILENAME $request_filename;
    }
}

location @api {
    rewrite /api/(.*)$ /api/index.php?/$1 last;
}

    error_page 500 502 503 504 /50x.html;
    location = /50x.html {
        root /usr/share/nginx/html;
    }

}
